# Generated by Django 5.2.10 on 2026-01-21 03:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0002_delete_participant_alter_event_participants'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='image',
            field=models.ImageField(blank=True, default='events/default_event.jpg', upload_to='events/'),
        ),
    ]
