# Generated by Django 5.2.10 on 2026-01-28 05:52

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0004_userprofile'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='userprofile',
            options={'verbose_name': 'User Profile', 'verbose_name_plural': 'User Profiles'},
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='bio',
            field=models.TextField(blank=True, help_text='Tell us about yourself', null=True),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='phone_number',
            field=models.CharField(blank=True, help_text='Enter phone number with country code (e.g., +1234567890)', max_length=17, null=True, validators=[django.core.validators.RegexValidator(code='invalid_phone', message='Phone number must be entered in the format: +1234567890. Up to 15 digits allowed.', regex='^\\+?1?\\d{9,15}$')]),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='profile_picture',
            field=models.ImageField(blank=True, default='profiles/default_profile.jpg', help_text='Upload a profile picture (JPG, PNG, GIF)', null=True, upload_to='profiles/'),
        ),
    ]
